---
title: "Test_GGSEG"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggseg)
library(patchwork)
library(tidyverse)
```

```{r}
# A: dk dark theme
fig2A <- ggseg(position = "stacked") +
  theme_dark() +
  labs (title = "dk",
  subtitle = "dark theme")

# B: dk medial view
fig2B <- ggseg(view = "medial") +
  labs (title = "dk",
  subtitle = "medial view")

# C: dk left medial alone
fig2C <- ggseg(view = "medial",
  hemisphere = "left") +
  labs(title = "dk",
  subtitle = "medial left")

# D: dk classic theme
fig2D <- ggseg(position = "stacked") +
  theme_classic() +
  labs (title = "dk",
  subtitle = "classic theme")

# E: dk left hemisphere
fig2E <- ggseg(hemisphere = "left") +
  labs (title = "dk",
  subtitle = "left hemisphere")

# F: aseg default theme
fig2F <- ggseg (atlas = aseg,
  view = "axial") +
  labs (title = "aseg",
  subtitle = "axial view")

```

```{r}
(fig2A + fig2B + fig2C) / 
  (fig2D + fig2E + fig2F) +
plot_annotation(tag_levels = "a")
```

```{r}
ggseg(mapping = aes(fill = region), colour = "black") +
  scale_fill_brain("dk") +
  theme(legend.justification = c(1, 0),
  legend.position = "bottom",
  legend.text = element_text(size = 5)) +
  guides(fill = guide_legend(ncol = 3))
```

```{r}
head(dk, 5)
```

```{r}
#yeo_repo <- ggseg_atlas_repos("Yeo")
#install_ggseg_atlas(yeo_repo$repo, yeo_repo$source)
```

```{r}
my_data = data.frame(
  region = c("control"),
  region_to_image = c("control"),
  stringsAsFactors = FALSE
)
str(my_data)

my_data

p <- ggplot(my_data) +
  geom_brain(atlas=yeo7, position=position_brain(hemi ~ side), mapping=aes(fill=region_to_image)) +
  scale_fill_brain2(yeo7$palette) +
  theme_brain2()

p


p <- ggplot(my_data) +
  geom_brain(atlas=yeo7, 
             position=position_brain(hemi ~ side), 
             aes(fill=region_to_image)) +
  scale_fill_brain2(yeo7$palette) +
  theme_brain2()

p


hazal_data = tibble(
  region = c("rostral anterior cingulate", "posterior cingulate", "medial orbitofrontal", "precuneus", "inferior parietal", "superior frontal", "rostral middle frontal"),
  region_to_image = c("rostral anterior cingulate", "posterior cingulate", "medial orbitofrontal", "precuneus", "inferior parietal", "superior frontal", "rostral middle frontal")
)

str(hazal_data)

p2 <- ggplot(hazal_data) +
    geom_brain(atlas = dk, 
               show.legend = FALSE,
               position = position_brain(hemi ~ side), 
               aes(fill = dk$atlas),
               colour="white") +
    theme_brain2() +
    scale_fill_manual(values = c("purple", "purple", "purple", "purple", "purple", "purple", "purple"), na.value="grey")

p2

p3 <- ggplot(dk$atlas)
p3
dk

ggplot() +
  geom_brain(atlas = dk) +
  guides(fill = guide_legend(ncol = 4)) +
  theme_void() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 2))

ggsave(filename = "/Users/stong3/Desktop/hazal_regions_figure.png", height = 4, width=7, dpi=300)


entor_data = tibble(
  region = c("hippocampus"),
  region_to_image = c("hippocampus")
)


p2 <- ggplot(entor_data) +
    geom_brain(atlas = dk, 
               show.legend = FALSE,
               position = position_brain(hemi ~ side), 
               aes(fill = region_to_image),
               colour="white") +
    theme_brain2() +
    scale_fill_manual(values = c("grey"), na.value="grey")

p2


```


```{r}
#Create a dataframe to hold the region we want to see (e.g. "cuneus" region from DK)
my_data = data.frame(
  region = c("cuneus", "precuneus", "rostral anterior cingulate", "superior parietal", "middle temporal", "isthmus cingulate", "entorhinal"),
  region_to_fill = c("cuneus", "precuneus", "rostral anterior cingulate", "superior parietal", "middle temporal", "isthmus cingulate", "entorhinal"),
  stringsAsFactors = FALSE
)

#Plot the brain using the dk atlas
p <- ggplot(my_data) +
  geom_brain(atlas=dk, position=position_brain(hemi ~ side), mapping=aes(fill=region_to_fill)) +
  #scale_fill_brain(name="dk") +
  scale_fill_manual(values = c("#DA0048", "#DA0048", "#DA0048", "#DA0048", "#DA0048", "#DA0048", "#DA0048"), na.value="white") +
  theme_classic()

p

p <- ggplot(my_data) +
  geom_brain(atlas=dk, position=position_brain(hemi ~ side), mapping=aes(fill=region_to_fill)) +
  #scale_fill_brain(name="dk") +
  scale_fill_manual(values = c("#DA0048", "#DA0048", "#DA0048", "#DA0048", "#DA0048", "#DA0048", "#DA0048"), na.value="white") +
  theme_classic()

p


p <- ggplot(my_data) +
  geom_brain(atlas=dk, position=position_brain(hemi ~ side), mapping=aes(fill=region_to_fill)) +
  #scale_fill_brain(name="dk") +
  scale_fill_manual(values = c("black", "black", "black", "black", "black", "black", "black"), na.value="white") +
  theme_classic()

p

```

```{r}
plot_region <- function(region, atlas){
  x = data.frame(
    region = region,
    region_to_fill = region,
    stringsAsFactors = FALSE
  )
  
  ggplot(x) +
    geom_brain(atlas = atlas,
               show.legend = FALSE,
               aes(fill = region_to_fill)) +
    scale_fill_brain2(atlas$palette) +
    theme_brain2()
    
}
yeo7$data

plot_region(c("control", "visual", "somatomotor", "dorsal attention", "ventral attention", "limbic", "control", "default"), yeo7)
```

```{r}
p <- lapply(c("visual", "somatomotor", "limbic", "dorsal attention", "default", "ventral attention", "control"), 
            plot_region, 
            atlas = yeo7)

wb <- plot_region(c("control", "visual", "somatomotor", "dorsal attention", "ventral attention", "limbic", "control", "default"), yeo7)

p1 <- patchwork::wrap_plots(p, nrow = 7)
ggsave("/Users/stong3/Desktop/Fingerprinting_Project/CAMCAN/05_Stats/02_Results/Objective 1 - Extra figure/Figure 1 - Network Representation.png", plot=p1, height=10, width = 8)

ggsave("/Users/stong3/Desktop/Fingerprinting_Project/CAMCAN/05_Stats/02_Results/Objective 1 - Extra figure/Figure 1 - Network Representation_Whole_brain.png", plot=wb, height=10, width=8)

```

